channels:
  - conda-forge
dependencies:
  - numpy
  - yaml
  - conda
  - xarray
  - scipy
  - configargparse
  - dask
  - h5netcdf
  - zarr=2.18
  - xarray-einstats==0.6.0
  - pytest
  - pytest-cov
  - python=3.11
  - numba
  - geopandas
  - rioxarray
  - flox
